### ISSUE TITLE
Error in `Tasks::Upgrade#upgrade_one`

### ISSUE THREAD

**Issue by dgreene-r7** [davepgreene/brew-cask-tools#2]
```
brew-cask-tools-1.0.1/lib/bct/tasks/upgrade.rb:49:in `upgrade_one': undefined local variable or method `cask_name' for #<BrewCaskTools::Tasks::Upgrade:0x007fb83b937f10> (NameError)
        from brew-cask-tools-1.0.1/lib/bct/tasks/upgrade.rb:23:in `initialize'
        from brew-cask-tools-1.0.1/lib/bct/tasks.rb:36:in `new'
        from brew-cask-tools-1.0.1/lib/bct/tasks.rb:36:in `upgrade'
        from thor-0.19.1/lib/thor/command.rb:27:in `run'
        from thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from thor-0.19.1/lib/thor/base.rb:440:in `start'
        from brew-cask-tools-1.0.1/bin/bct:4:in `<top (required)>'
        from bin/bct:23:in `load'
        from bin/bct:23:in `<main>'
```

**Comment by davepgreene** [comment]
Fixed in 44092f8.
